# Generated by Django 3.1.12 on 2025-01-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_surname', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('from_country', models.CharField(max_length=100)),
                ('to_country', models.CharField(max_length=100)),
                ('cargo_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('agree_privacy_policy', models.BooleanField(default=False)),
                ('agree_promotions', models.BooleanField(default=False)),
            ],
        ),
    ]
